### PR TITLE
show the SNR above the real time chart

### PR DESCRIPTION
**Pull request by tpaskett**
this is very helpful when your on the tower and you have someone below reading you the SNR to optimize the tilt. hard to tell exactly from the chart other than better / worse. i coded / tested this on 3.16.1.0, so will have to test that it works with the changes that were made to www/cgi-bin/signal since 3.16.1.0

### CODE REVIEW

**Comment by dman776** [comment]
This doesn't appear to work on 3.16.2.0RC1.

**Review by dman776 — CHANGES_REQUESTED** [review]
still fails on the lastest develop branch code.
Javascript error in signal 
dps[1] does not exist.
from line:   dps[1].push(result[1][0]);

signal.json only returns one element in that array. dps[0]

**Review by tpaskett — COMMENTED** [review]
this works for me against nightly build 186-8d3b63a

**Review by dman776 — APPROVED** [review]
works fine on nightly

**Pull request merged**
