### PR TITLE
Added base support for TP-Link WBS210 router

### PR DESCRIPTION
**Pull request by patrickdickey52761**
My username on Github was set before I started with this project, so it doesn't reflect my call sign. KE0RSX. If necessary, I can re-fork the branch under my call sign, or create a new account on here to use my call sign. Also, I should note that on February 16, 2019, my call sign will most likely be changing to W0PCD.
The main TO DO: for this device is fixing the issue where both LAN ports are bridged if cables are connected to them when the device is booted up, instead of being separate. Also, in the changes, it shows 18 deletions. I didn't perform any deletions (or wasn't intending to). So I can fix that if necessary.

### CODE REVIEW

**Comment by ae6xe** [comment]
Patrick,  can you attach back the output of:
1) "swconfig dev switch0 show"
2) "swconfig dev switch0 help" 

Yes, the deletions should not be in this commit.  Add these lines back in and ether add a 2nd commit or do a commit with a --amend option (and --force to push up to your github fork).

**Comment by ae6xe** [comment]
Patrick,   I've applied this series of patches and still getting an end result with some duplication of entries.    It may be best to do a clean local repo, modify the 3 files, and check in a new clean PR and cancel this current one.   Alternatively, I can see the intended changes and I could do a commit attributed to you.

**Comment by patrickdickey52761** [comment]
Hi, Joe,

 

It’ll probably be easier if you do the commit. It seems like every time I try to do it, some random crap happens. This last time, it inserted the 18 lines that were deleted, and then put an extra = in line 4 (= for comment).

 

I will try a clean repo though and see if I can get it working later.

 

Have a great day, and thank you for being patient with this. 😊
Patrick.

 

P.S. Now, I can’t reproduce the issue with the LAN ports being bridged. I’m starting to think it’s my computer.

**Comment by ae6xe** [comment]
patrick,  send me your email address you want to use to sign the commit with.   callsign at arrl dot net.

**Comment by patrickdickey52761** [comment]
Hi, Joe,

 

KE0RSX@arrl.net <mailto:KE0RSX@arrl.net>  is my email address there. In 10 days, I *should* have a vanity (W0PCD), so after that it will change.

 

Have a great day and thank you again. 😊
Patrick.

 

P.S. Just so you know that doesn’t redirect to the email address that I have Github set up with. If I need to set things up so it does, I can.

**Comment by patrickdickey52761** [comment]
Hi, Joe,

 

I just deleted my fork and re forked the project. I’m going to try and make the changes once more and see what it does. Assuming that it doesn’t add any weird things, or remove stuff that should be there, I’ll try to commit it again. In your original email you asked me for the output of "swconfig dev switch0 show" and "swconfig dev switch0 help". Was the in reference to my issue with the LAN ports or was that something you were seeing in my commits? If it’s the LAN ports, I don’t think it was a real issue. I think it was something on my computer only. 

 

Have a great night. 😊
Patrick.

 

P.S. If everything works, I’ll probably have a pull request before 8 p.m. tonight. Otherwise I would say go ahead and use what I had already sent in, if you still have it.

**Comment by ae6xe** [comment]
PR will be resubmitted shortly.

**Pull request closed without merging**
