### PR TITLE
Trim Packages

### PR DESCRIPTION
**Pull request by r1de**
Kernel support for USB has been moved to modules
libpcap and tcpdump have been moved to modules
libnetsnmp and snmpd have been moved to modules
IPv6 has been removed from the kernel
IPv6 support has been removed from busybox network utils as well.
(no more funny DNS responses in nslookup! Remember issue #85 ?)

Please take a look, some of the options for IPv6 and busybox are probably redundant.
Image file is at ~~5.7MB~~ 5.6MB with this config.

### CODE REVIEW

**Comment by r1de** [comment]
There might be some other things that can be removed from busybox as well.
"dd", do we really need "dd" on the node?
"ls" with colors, sure it's nice, but is it really needed?
"chroot", etc...etc...

**Comment by r1de** [comment]
Additional patch file to stop busybox from making ping6 and traceroute6 since they'd no longer be needed.
Adding CONFIG_BUSYBOX_CONFIG_PING6=n into common.config did not seem to do anything.
Busybox had to be forced to default to not creating ping6 and traceroute6.

**Comment by dman776** [comment]
If I recall, i think the dd command is used in the get_hardware (or get_model) script.  That needs to remain.

**Review by dman776 — COMMENTED** [review]
Need to re-number the busybox patch to proper numbering structure (check the readme.md file).
also, need to add it to the patches/series file so that the build will apply it.

**Review by ae6xe — COMMENTED** [review]
[edit]   nevermind, I see you already tried this, should have read the full history :) first.  

Please see if you can instead  edit the configs/common.config and specify what the setting should be:

CONFIG_BUSYBOX_DEFAULT_TRACEROUTE=n
CONFIG_BUSYBOX_DEFAULT=TRACEROUTE6=n

Probably a patch to openwrt is not needed, rather a config file setting.

**Comment by ae6xe** [comment]
Yes, 'dd' is used in a few places to dig though flash memory looking for specific memory locations to pull out settings or identify the device.

**Comment by ae6xe** [comment]
note, this removal of IPV6 was done once before, just not ported forward yet.  Darryl, I think you did that, so assume the changes here are equal to or greater than what was done before.  

I ran into a global compile option in "make menuconfig" a couple months ago to exclude compiling in code to all the packages/models/etc related to ipv6.   Is this how the options in this PR were determined?  Could there be more options to include?

**Comment by r1de** [comment]
@dman776 Thanks! I will look at the numbering, I just put 999 so as to not get in the way of the others.
Once I created the patch file, it seemed like it got picked up at build time without me doing anything, but I will check that too.

I will forget about removing "dd".
You guys got me thinking of how to really slim it down and I might get over zealous a bit, sorry.
I come from an old line of people who, even still, build our own kernels for most of our linux machines, I know, I'm crazy, it's fun! :smile:

@ae6xe I determined the needed options from looking at both the .config file and from the "Help" area of "make menuconfig", and it seems they are sometimes different, and like busybox, some seem to work and others (that you'd think should) won't.
I could have been having a PEBKAC issue though. :smile: 
*edit*: and yes Joe, there are probably many other options that could be used to clean things up a bit, remove certain commands that no one will need (or get into trouble with), etc..etc...

I also think the order might matter in common.config, but I haven't really determined that to be the case yet... It's just a hunch.

**Comment by dman776** [comment]
the build seemed inconsistent, but, not sure if it is related to this PR or not.  I did need to 'make' twice to get this to build completly (using the official "clean" docker container).  Loaded on Rocket M2 successfully.
Loaded SNMP packages.  Looks like the /etc/config/snmp is different now.

--------
Installing snmpd (5.7.3-9) to root...
Collected errors:
 * resolve_conffiles: Existing conffile /etc/config/snmpd is different from the 
conffile in the new package. The new conffile will be placed at
/etc/config/snmpd-opkg.
Configuring snmpd.
------

**Review by dman776 — APPROVED** [review]
Tested ok on Rocket M2.

**Review by ae6xe — APPROVED** [review]
looks good.

**Pull request merged**
