### PR TITLE
Add "Advanced config" page

### LINKED ISSUE #230: Add ability in Settings to define a location for locally hosted images and packages
Some mesh networks do not connect to the internet and are unable to 'refresh' in the Administration page to ease the ability to find and install newer firmware versions or install add-on packages.   Add a setting to enable definition of other locally hosted "download" web servers.    Instead of a  built in path of "http://downloads.arednmesh.org/releases/3/18/3.18.9.0/",  a group could clone these files and put locally on a web server at, e.g. "http://ae6xe-downloads.local.mesh/3.18.9.0".

### PR DESCRIPTION
**Pull request by dman776**
Adds settings for leafletjs, leafletcss, maptiles, and firmware download location
fixes #230

### CODE REVIEW

**Comment by ae6xe** [comment]
not seeing the default settings for serverpath:
image

**Comment by dman776** [comment]
what is in /etc/config.mesh/system for section aredn/option serverpath??

**Comment by ae6xe** [comment]
On the live node:

config aredn
        option serverpath 'http://downloads.arednmesh.org/firmware/ubnt'

**Comment by ae6xe** [comment]
after copying up the modified files, I probably need to "save" settings.  This isn't in /etc/config/system.

**Comment by dman776** [comment]
correct.   if you are testing by copying the files in, the default is in config.mesh and you will need to SAVE SETTINGS to copy then to the live config in /etc/config

**Review by ae6xe — APPROVED** [review]
I tested on an hap ac lite.   changed firmware download to a local web server.  all worked as expected.

**Pull request merged**
