### PR TITLE
hardware: add aredn definition for mikrotik 912uag-5hpnd

### PR DESCRIPTION
**Pull request by ae6xe**
Mikrotik RouterBOARD 912UAG-5HPnD or BaseBox 5 definition

### CODE REVIEW

**Comment by dman776** [comment]
have you checked the /usr/local/bin/get_model  (get_hardwaremfg, get_boardid) scripts to see what they return?

**Comment by dman776** [comment]
also need to update the post build tests for the additional output files

**Comment by ae6xe** [comment]
All looks good on the "get_*" output:
========== /usr/local/bin/get_hardwaretype ==========
rb-912uag-5hpnd
========== /usr/local/bin/get_boardid ==========
Mikrotik RouterBOARD 912UAG-5HPnD
========== /usr/local/bin/get_model ==========
Mikrotik RouterBOARD 912UAG-5HPnD 
========== /usr/local/bin/get_hardware_mfg ==========
Mikrotik

**Comment by ae6xe** [comment]
There will need to be another commit to address 3 known issues:
1) config.mk needs changed from TARGET=ar71xx-generic to TARGET=ar71xx-mikrotik, they don't build at the same time (or build together).  This may be a 2nd full build or might be a way to do this with image builder after the generic images build. (and included a new file configs/ar71xx-mikrotik.conf)
2) the LED lights aren't AREDN coordinated yet.
3) I just found that OLSR is not propagating the hostname, but is propagaing the dtdlink name for some reason.

I can build on this PR or be separate, any preference?

**Comment by dman776** [comment]
i think this PR should include EVERYTHING to enable this new device (912uag-5hpnd).

**Comment by dman776** [comment]
Joe, i thought you added some additional changes to this.  it shows that it has not been updated in 25 days or so.

**Comment by ae6xe** [comment]
I think the 25 days is the original commit timeframe.  I'm seeing a change showing in the PR commit that I made this past weekend.

**Pull request merged**
