### PR TITLE
config change to make uhttpd listen on port 80 and 8080

### PR DESCRIPTION
**Pull request by tpaskett**
its time to do this. i'm tired out having to teach new people to mesh how to type in the url and they always forget, especially during our emergency exercises. port 8080 does not make it more secure. it is also very unlikely users have the external interface using a public internet ip address. this change makes it work on both port 8080 for backwards compatibility and port 80 that most users are used to.

### CODE REVIEW

**Review by ae6xe — APPROVED** [review]
I agree.

**Comment by dman776** [comment]
Do firewall rules need to change?

**Comment by ae6xe** [comment]
good catch, yes need an update to the default firewall rules in the config files and in /etc/local/mesh-firewall/01-tunnels.

**Review by dman776 — CHANGES_REQUESTED** [review]
needs firewall adjustments

**Review by ae6xe — COMMENTED** [review]
several more places in etc/config*/firewall.

**Comment by ae6xe** [comment]
also update to www/help.html of both ports.

**Review by tpaskett — COMMENTED** [review]
someone could do better on the help text im sure.

**Comment by ae6xe** [comment]
better grep 8080 to find all the occurrences.  The  etc/config*/firewall files have it in 3 places, 2 more to go  -- to be accessed coming in over wifi, wan, and dtdlink.    We got the incoming from tunnel already .

**Review by tpaskett — COMMENTED** [review]
think i have all of them now

**Comment by ae6xe** [comment]
Looks good to me.

**Review by dman776 — APPROVED** [review]

**Comment by dman776** [comment]
looks good.

**Comment by Orv** [comment]
This works fine (thanks, Trevor!).   I noticed that the broadcasted URL still advertises on port 8080. Should this be changed to 80?

**Comment by dman776** [comment]
no, because other V3 protocol nodes expect them on 8080.   This is just for convenience.

**Pull request merged**
