### PR TITLE
bugfix: Check for existing hostnames on the network in DHCP reservations

### LINKED ISSUE #216: Avoid duplicate hostnames when reserving IP addresses
Generic hostnames can be created across the mesh network, e.g. "RPi", "RasPBX", "ipCam", etc.,   If duplicate, one device may not be reachable.    Check if an existing hostname already exists for reserving an IP address.

### PR DESCRIPTION
**Pull request by r1de**
fixes #216
*additional check for existing hostname when creating new DHCP lease.
checks hosts_olsr file if entered hostname already exists or not on the connected network(s).
outputs info saying such and gives advice to prefix hostname with callsign.

### CODE REVIEW

**Review by ae6xe — CHANGES_REQUESTED** [review]
The error message when displayed is chopped off.  it only shows the first line, "hostname `xyz` is already in use".     The other 2 lines aren't shown -- remove from code or find a way to show them.   (I'm using chrome.)  

Also, not sure why this code works with different combinations of upper and lower case letters, e.g. it still finds duplicate with "XYZ" and "xyz".   The line with "/\t$host\t/" may need explicit case insensitive match, "/\t$host\t/i" to be sure.    Maybe case insensitive mode has been turned on somewhere else somehow?

**Comment by ae6xe** [comment]
image

**Comment by dman776** [comment]
the default match is case-sensitive.   You certainly need the /xxxx/i   syntax to disable it.

**Comment by ae6xe** [comment]
Also,  should probably use "/s" instead of "/t".   May not be guaranteed to always have a tab char.

**Comment by r1de** [comment]
copy that...
I bet the text is getting truncated when the lease list is already large... (I only tried it on a test node with no other leases)

I'll try it on one line, but I'm not sure that'll do it... (or try to shorten the message)

**Comment by r1de** [comment]
I wonder if it is just after that 5th/6th entry:
arednhostnametest02

I'll try to track that down...
Never say "that looks easy!" :)
(this is with firefox on linux)

**Comment by r1de** [comment]
`/\s$host\s/i`
sorry for typo in the commit

**Comment by r1de** [comment]
Tested the warning message on every browser I have in my house, chrome, firefox, *cough* IE, etc..
I've used tablet(s), phone(s), and PC(s).
I do not see the warning being truncated with any of them...

Is anyone else seeing the same behavior Joe is seeing?

Joe, can you check and make sure you have the latest code for this PR? I think you somehow have an older version of it.

**Comment by ae6xe** [comment]
That was the original code submitted and results.  I'll retest tonight with current code.

**Comment by r1de** [comment]
Ok, Thx. I'll double check I submitted the correct stuff (I am pretty sure I did).
It's just odd that you don't even have the "Warning!" part of the text. 

```
          push(@dhcp_err, "$val <font color='red'>Warning!</font> '$host' is already in use!<br>" .
            "Please choose another hostname.<br>" .
            "Prefixing the hostname with your callsign will <em>ensure</em> it is unique.") if $foundHost == 1;
```
(above code copied from here: https://github.com/aredn/aredn_ar71xx/pull/226/files )

**Comment by dman776** [comment]
Change: "Prefixing the hostname with your callsign will <em>ensure</em> it is unique."
to: "Prefixing the hostname with your callsign will help prevent duplicates on the network."

**Comment by ae6xe** [comment]
I'll inspect the code still on my test node to make sure there's not an
error in how I copied code down and installed.  Could a long hostname be a
factor, pushing the string outside of edges?

**Comment by r1de** [comment]
> I'll inspect the code still on my test node to make sure there's not an error in how I copied code down and installed. Could a long hostname be a factor, pushing the string outside of edges?

I think it'll just word wrap it to fit into the "area". My long sentences have been getting wrapped, I'd imagine a long hostname would be treated the same...

and copy that, @dman776 that wording does sound better.

**Comment by ae6xe** [comment]
I'm getting this with the latest.   
image

**Comment by r1de** [comment]
Ouch! that's what I get for testing this on a node with no other reservations! :smile:
That's a bit crazy that they *all* get validated every single time...
I think I know what it is...

maybe I can even catch existing dupes now tho.

**Comment by r1de** [comment]
@ae6xe try it now. It should not do that anymore.
I was trying to also catch any existing duplicate hostnames, but it was not working, I'm sure I am just doing it wrong.
This will only catch *newly added* hostnames that are duplicates...

**Review by ae6xe — APPROVED** [review]
tested on hAP ac lite.  worked as expected.

**Pull request merged**
