### PR TITLE
aredn: stop cron prior to starting sysupgrade

### PR DESCRIPTION
**Pull request by ae6xe**

### CODE REVIEW

**Review by dman776 — APPROVED** [review]
looks good.

**Comment by Orv** [comment]
What's the rationale behind this?  (Just curious).

**Comment by dman776** [comment]
This should eliminate the "failed" sysupgrade issue where after a load attempt, the node is still at the same version as before.

**Comment by ae6xe** [comment]
We found that when preparing to do the upgrade process, and programs and RAM were freed up, that cron was restarted by procd (or stayed running) and was continuing to starting up new processes in the opposite direction causing havoc on 32MB RAM devices.

**Pull request merged**
