### PR TITLE
feature: add bootloader version to supporttool output

### PR DESCRIPTION
**Pull request by dman776**

### CODE REVIEW

**Review by ae6xe — COMMENTED** [review]
On Mikrotik, there are 2 bootloaders (one that can be updated and one that is read only to guarantee a fall back).   Thus in the future, we'd want to test for the platform to report this additional information.   Should we template out this platform test now and only run on on ubnt out of the gate?

**Comment by dman776** [comment]
not a bad idea.  Is there an existing mechanism to show the manufacturer?   /usr/local/bin/get_boardid shows it as part of the string, but, i don't trust that across all the manufacturers.  Looking for something that returns: ubnt, tplink, mikrotik, etc.

**Comment by dman776** [comment]
examples of get_boardid output:
TP-Link CPE210 v1.0
Ubiquiti Nanostation M

if I had to, I could parse the up to the first space to get the mfg.

**Comment by ae6xe** [comment]
check on a device in the /etc/board.json data.  If there is a unique or best object to key off, this file would tell us.  All of the downstream tools/commands, get_boardid, etc. pull from this master data.

**Comment by dman776** [comment]
ok.  i added a get_hardware_mfg script that pulls/parses from board.json.  Added cmds_ubnt sections to supporttool.

**Comment by ae6xe** [comment]
dman776, it installed (from a full image build process) but did not end up with 755 permissions on /usr/local/bin/get_hardware_mfg file.  Consequently, it says permission denied when I try to run it manually and there is no output in the support download (only the header).

**Comment by dman776** [comment]
Hmm.  I explicitly set permissions before I committed.  At least I thought I did. Will check tomorrow 

Thanks,
Darryl

**Comment by ae6xe** [comment]
then it should be good.   The issue I'm seeing must be due to how I pulled down the change in patch format, which isn't going to set the file permissions.

**Pull request merged**
