### PR TITLE
Update contributors file

### PR DESCRIPTION
**Pull request by dman776**
Adding Jason and Eric.
@jbrady42 
@r1de

### CODE REVIEW

**Comment by wu2s** [comment]
OK accepted

**Review by K6AH — COMMENTED** [review]
Jason doesn't leave much of a trace behind, does he?  I don't even find a record of him on our website.  I guess you don't need to be registered to fork the project.

It would be nice to get his callsign.

**Comment by dman776** [comment]
I already left a comment on PR #73 asking him for that info.

**Comment by K6AH** [comment]
I'd like to wait a day to see if he responds before I approve the change.

**Comment by jbrady42** [comment]
Thanks for the mention. My call is KF5DEB, email at kf5deb@arrl.net

I registered on the site a while back and have been following development on and off. It's good to see the project moving forward and will help out where I can.

**Pull request merged**
