### PR TITLE
feature: add aam_refresh method to advanced config page

### PR DESCRIPTION
**Pull request by dman776**

### CODE REVIEW

**Review by ae6xe — APPROVED** [review]
look good.

**Comment by Orv** [comment]
What does this do?

**Comment by ae6xe** [comment]
It is a companion to this feature:  https://github.com/aredn/aredn_ar71xx/pull/505

**Comment by ae6xe** [comment]
In anticipation, #505 is a feature to enable an AREDN mechanism to display notices or announcements globally and/or by individual node name to mesh nodes that have access to the internet.    The node will check if there is access to the internet, if so, then download these messages and display in node status.

**Comment by Orv** [comment]
Thanks.

Orv

**Comment by dman776** [comment]
FYI, for the AREDN Alert Message system:   https://arednmesh.readthedocs.io/en/latest/arednGettingStarted/node_status.html#node-and-broadcast-messages

**Pull request merged**
