### PR TITLE
aredn: olsrd: add olsrd watchdog

### LINKED ISSUE #338: Add olsr watchdog
If olsr locks up or blocks for any reason, the node would not be reachable over the mesh.  Currently, olsr is only restarted if the process no longer exists.  This request is to add a safety net to restart olsr if it is still running, but not processing events.   If such an unexpected event happens, olsr would be restarted, and mesh nodes at hard to access tower sites would still be reachable,

### PR DESCRIPTION
**Pull request by ae6xe**
Adding native olsrd watchdog on top of procd
ensures mesh nodes are always accessable.

closes #338

### CODE REVIEW

**Review by dman776 — COMMENTED** [review]
Is the 5sec interval too quick.   Seems like 60 would be sufficient

**Comment by ae6xe** [comment]
The check to do the olsr restart is at 21 seconds intervals, giving olsr multiple attempts to touch this watchdog file.  A total time to recover node would be about ~50 seconds.  There can be timing issues when olsr is starting up, and to be conservative, we give olsr multiple opportunities to tickle the watchdog file.    If we changed it to,e .g. 60 seconds, then we'd also want to then only trigger a reset after 3+ minutes, which translates to a recovery time of 3.5+ minutes.    

In argument of the current value, the processing by olsr is relatively trivial -- it is touching a file in RAM.   I'd propose ether leave it as is, or a middle ground of say 20 sec tickle and 70 sec reset threshold, total recovery time about 100 seconds.

**Comment by ae6xe** [comment]
minor update to touch the log file at start so the support download doesn't have error when file doesn't exist.

**Review by dman776 — APPROVED** [review]
Looks good

**Pull request merged**
