### PR TITLE
feature: added a wifi scan endpoint to the /api

### PR DESCRIPTION
**Pull request by mcleanra**
this is for #264 , i'll make another PR to aredn_ui shortly with a scan interface that depends on this.  i've only done testing on a nanostation m2

### CODE REVIEW

**Comment by mcleanra** [comment]
sent the other related pr: https://github.com/aredn/aredn_ui/pull/12

**Comment by dman776** [comment]
First, thank you for the PR!   Happy to see it.   
what's the thought process behind modifying wscan to add json output, instead of adding code to /api to output scan info (ie.   http://localnode.local.mesh:8080/cgi-bin/api?status=scan      or similar).   The iwinfolua library is available and should contain all the data needed.   It seems that the only reason to add the json scan output is to feed the AngularUI and the /api is the primary data source for that.

**Comment by mcleanra** [comment]
hi @dman776 
that certainly makes sense, thanks for the heads up on the /api approach.  i'm not really that familiar with lua but i took a crack at it and updated the PR by adding a new /api endpoint for the scan page (http://localnode.local.mesh:8080/cgi-bin/api?scan=scanlist).  

i'll modify the angular PR pending your thoughts on this approach

**Comment by ae6xe** [comment]
Ryan,  can you send an email to ae6xe at arrl dot net?   We can setup additional realtime communications to have more interactive dialog on UI changes beyond what we'd want to capture in a github PR.

**Comment by dman776** [comment]
We need to decide how to handle the non-standard channels (ie.   ch254 is ch-2, ch255 is ch-1, 3Ghz channels, etc)....   Need to discuss if we patch iwinfo, libiwinfo-lua, or translate in /api.   Holding pending further discussion.

**Comment by mcleanra** [comment]
We could always expose ```freqlist``` through the API and use that info to do a transform client side with a custom pipe.  Basically the same thing wscan currently does in ```freq_to_chan```

As a bonus we would be able to show what frequencies the device supports, maybe somewhere on the status page

**Review by dman776 — APPROVED** [review]
will need to ensure that we create a pipe in the UI to translate non-standard channels to negative channels

**Pull request merged**
