### PR TITLE
Fw upload area enhance

### PR DESCRIPTION
**Pull request by r1de**
aredn: Info about the device and firmware type needed added above the firmware uploading buttons.
Even I have to double check which firmware is for which device sometimes.
This will hopefully help to alleviate any confusion, and save a few people some sanity. :)

Also got rid of a warning in the syntax checking routines (03-cgibin_admin).

### CODE REVIEW

**Comment by ae6xe** [comment]
I just checked on the Mikrotik gear.  Unfortunately,  this will show up with the device model detail:   get_hardwaretype on a basebox 5 shows 'rb-912uag-5hpnd".    on the hAP lite, the same.    The dmesg detail on mikrotik doesn't help ether.  It shows board=711Gr100.    2 options I can think of, A) don't show anything; B) create a mapping table of model # to image name to show.

**Comment by r1de** [comment]
Ok. good catch Joe.
"more work to be done"
We'll show nothing for now.

I am removing the PR while I work on this some more.

**Comment by Orv** [comment]
Could you not enable this PR for Ubiquiti products only, for now?  And once the Mikrotik issue is resolved enable it for them?  Does it work on TPLink?  If no, the same reasoning would follow.

**Comment by ae6xe** [comment]
It's common code.  With such limited non-ubnt models, it would be minor difference between a check for these models and take corrective action vs check for these models and not do anything.

**Pull request closed without merging**
